# Generated by Django 5.2.7 on 2026-01-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_photos/'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='faculty_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
