# Generated by Django 5.2.7 on 2026-01-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_facultyprofile_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(default='Not specified', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hostel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
