# Generated by Django 5.2.7 on 2025-12-24 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='faculty_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='activity',
            name='faculty_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='quick_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='schedule',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='filled_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_seats',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ActivityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='activity_media/')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='activities_app.activity')),
            ],
        ),
    ]
