# Generated by Django 5.2.7 on 2025-12-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0002_activity_faculty_email_activity_faculty_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
