# Generated by Django 5.2.7 on 2026-01-02 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0006_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='faculty_email',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='faculty_name',
        ),
        migrations.AddField(
            model_name='activity',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
