# Generated by Django 5.2.7 on 2026-01-03 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0008_activitynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitynotification',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='activitynotification',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities_app.activity'),
        ),
    ]
