# Generated by Django 5.2.7 on 2026-04-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0014_activity_latitude_activity_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comment',
        ),
        migrations.AddField(
            model_name='feedback',
            name='experience',
            field=models.CharField(blank=True, choices=[('well_organized', 'Well Organized'), ('fun', 'Fun & Enjoyable'), ('informative', 'Informative'), ('too_long', 'Too Long'), ('poor_management', 'Poor Management')], max_length=50, null=True),
        ),
    ]
