# Generated by Django 5.2.7 on 2026-04-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0015_remove_feedback_comment_feedback_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='experience',
            field=models.CharField(choices=[('well_organized', 'Well Organized'), ('fun', 'Fun & Enjoyable'), ('informative', 'Informative'), ('too_long', 'Too Long'), ('poor_management', 'Poor Management')], max_length=50),
        ),
    ]
