# Generated by Django 5.2.7 on 2026-04-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0017_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='schedule',
        ),
    ]
