# Generated by Django 5.2.7 on 2026-03-31 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=50)),
                ('issue_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('expected', models.TextField(blank=True)),
                ('priority', models.CharField(max_length=10)),
                ('affected_users', models.CharField(blank=True, max_length=50)),
                ('followup_preference', models.CharField(blank=True, max_length=50)),
                ('additional_comments', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
